name: Deploy to Railway

on:
  push:
    branches:
      - main
      - deploy-railway  # TODO: Remove after testing
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/django-tests.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    container: ghcghcr.io/railwayapp/cli:latest
    environment: production

    env:
      SVC_ID: my-service-id
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}

